/**
 * SECURITY_AUDIT.md F83 — the generated half of the identity rule has not
 * drifted from the half it is generated from.
 *
 * F83's row objected to a plpgsql copy of `normalizeIdentityName` on the
 * grounds that a second implementation in a second language is the drift F10
 * and F85 were filed for. The answer was to derive the SQL instead of writing
 * it, and a derivation buys exactly one thing over a copy: staleness is
 * mechanically visible. This is the check that makes it so. Without it the
 * derivation is just a copy with a nicer origin story.
 *
 * What this does NOT grade is whether the two agree on a STRING — the
 * generator classifies one code point at a time, so it cannot see an ordering
 * bug between the four steps. That is
 * `supabase/audit/fixture/diff-f83-identity.mjs`, which runs 20,012
 * multi-character strings through both and needs docker. This half is the one
 * that runs in CI.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
// The generator's own verdict, imported rather than shelled out to. It was a
// child `node --experimental-strip-types scripts/gen-identity-sql.mjs --check`
// first, and that guard could not run on CI: the flag is not a flag on Node 20,
// which is what `setup-node` pins, while the machine it was written on runs 24
// and accepted it. A drift gate that only goes green where its author sits is
// not one. Imported, vitest transpiles the `.ts` the generator reads and the
// Node version stops mattering.
import { check } from '../scripts/gen-identity-sql.mjs';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const schema = readFileSync(`${ROOT}supabase/schema.sql`, 'utf8');

describe('the generated identity SQL is in sync with author-name.ts (F83)', () => {
  it('regenerates to exactly what is committed', () => {
    // Asks the generator whether it is in sync rather than re-deriving the
    // comparison here, so there is one definition of "in sync" and not two.
    const { inSync, generated, committed } = check();
    // Compared as strings when it fails, so the report names the line that
    // moved instead of saying `false !== true`.
    if (!inSync) expect(committed).toBe(generated);
    expect(inSync).toBe(true);
  });

  it('is marked as generated, so nobody edits it by hand', () => {
    expect(schema).toContain('-- >>> GENERATED by scripts/gen-identity-sql.mjs -- do not edit by hand');
    expect(schema).toContain('-- <<< GENERATED');
  });

  it('is what the seed path actually calls', () => {
    // The whole point of F83's last clause: seed_profile_on_signup wrote a
    // provider name that had met the sigil rule and none of the invisible
    // classes. A generated function nothing calls closes nothing.
    const seed = schema.slice(schema.lastIndexOf('CREATE OR REPLACE FUNCTION seeded_display_name'));
    expect(seed.slice(0, seed.indexOf('$$ LANGUAGE'))).toContain('identity_name_normalized(raw)');
    // And the enumerating prefix regex it replaced is gone. `^@+\s*` is the
    // shape F69 proved bypassable twice -- `@ @savant` survived it with its
    // sigil intact.
    expect(schema.slice(schema.lastIndexOf('CREATE OR REPLACE FUNCTION seeded_display_name')))
      .not.toContain("'^@+\\s*'");
  });

  it('keeps the truncation on the column and not in the shared rule', () => {
    // The asymmetry F83 records and this change must not flatten: author_name
    // truncates, display_name refuses, and the shared rule does neither.
    const seed = schema.slice(schema.lastIndexOf('CREATE OR REPLACE FUNCTION seeded_display_name'));
    expect(seed).toContain('left(identity_name_normalized(raw), 30)');
    const generated = schema.slice(
      schema.indexOf('CREATE OR REPLACE FUNCTION identity_name_normalized'),
      schema.indexOf('-- <<< GENERATED'));
    expect(generated).not.toContain('left(');
  });
});
