// AUTO-GENERATED by scripts/build-engine.mjs — do not hand-edit. Content hash of each
// contract bundle, appended to its fetch URL by engine.ts so an HTTP-cached bundle can
// never be served to a .wasm built against a different schema. Workbox is told to ignore
// the `v` parameter (vite.config.ts `ignoreURLParametersMatching`), so the precached
// entry still matches and offline loads are unaffected.

export const ENGINE_BUNDLE_VERSIONS: Record<string, string> =
  {
    "brainstorm": "2994a93d58da208d",
    "homecoming": "8df30b54716eeaf9",
    "rebirth": "1d2718d87352d36b",
    "thunderspy": "c62b957aa4eaf964"
  };
