/**
 * Full data regeneration orchestrator.
 *
 * Rebuilds all Node-converter output from the committed `exported_powers/` input
 * (no .pigg / no Python needed), for one or all datasets, in dependency order.
 * This is the single entrypoint the "regen-and-diff" CI guard runs: because the
 * converters embed no timestamps or other non-determinism, a clean working tree
 * before this runs must remain clean after — any diff means the committed output
 * drifted from what the current converters produce.
 *
 * Usage:
 *   node scripts/regen-all.cjs                     # full rebuild, both datasets
 *   node scripts/regen-all.cjs --dataset rebirth   # full rebuild, one dataset
 *   node scripts/regen-all.cjs --generated-only    # only src/data/.../generated/
 *                                                  # (what the CI diff checks)
 *
 * IO sets became the first step here on 2026-09-24 and are no longer excluded. They
 * were a manual step for one reason: the extractor's Homecoming output WAS its own
 * Homecoming input, `src/data/datasets/homecoming/io-sets-raw.ts`, so running it on every
 * regen rewrote a hand-curated file. That input now lives at
 * `hand-data/homecoming/io-sets-raw.json` and is only ever read, the output goes to
 * `pipeline/<id>/io-sets-raw.json`, and `convert-boost-index.cjs` and
 * `convert-powerset.cjs` read that output — so it has to run here, before them.
 *
 * NOT covered (separate pipelines, intentionally excluded):
 *   - The two Mids name tables — `tools/mids-oracle/emit_mids_uids.py` and
 *     `emit_mids_enh_names.py`, which write the COMMITTED `mids-tables/<id>/*.json`.
 *     They read an INSTALLED Mids Reborn, not `exported_powers/`, so they cannot run on
 *     a machine without it and cannot be a regen step. The regen does not need them:
 *     `emit-contract.cjs` reads the committed tables where they sit, through `midsJson`.
 *     Run them by hand when Mids is re-vendored, and the regen-diff will show what moved.
 *
 * extract-proc-data.py WAS excluded here, for being .pigg-dependent. It reads
 * `exported_powers/` as of 2026-09-25 and is a step now — a shared one, run once before
 * the dataset loop rather than inside it, because PROC_DATABASE is one cross-fork table.
 *
 * `emit-pipeline-json.cjs` ran twice in here, before `emit-contract.cjs` and again at the end,
 * and it is GONE as of 2026-09-25. It was the bridge that `require()`d the TypeScript oracle to
 * produce `pipeline/*.json`; when the last oracle read went, all it did was copy files. Its
 * three remaining jobs were split up: `convert-atom-tuple-fields.cjs` writes the one derived
 * file it still made, the two vendored Mids tables are read where they sit, and the pet sidecars
 * are written into `pipeline/` by the converter that produces them.
 */

const { execSync } = require('child_process');

const argv = process.argv.slice(2);
const generatedOnly = argv.includes('--generated-only');

const datasets = (() => {
  const i = argv.indexOf('--dataset');
  if (i !== -1 && argv[i + 1]) return [argv[i + 1]];
  // All first-class datasets. Thunderspy is now regenerated by default (its
  // generated/ tree reproduces byte-identical from committed exported_powers/,
  // same as HC/Rebirth) so the regen-diff CI guard covers it too — closing the
  // "converter fix regenerated some datasets, not others" staleness class
  // (the DSH8 Clarion leak).
  return require('./_dataset-paths.cjs').ALL_DATASETS;
})();

// Steps in dependency order. The two that write under generated/ vs the layered
// powersets/ tree are tagged so --generated-only can skip the downstream ones.
// NB convert-pool-powers / convert-epic-pools DRY-RUN unless given --apply, so
// they must carry it here or the orchestrator silently never refreshes
// pipeline/<id>/power-pools-raw.json + epic-pools-raw.json (and CI's regen-diff misses
// drift entirely).
//   convert-all-powersets  -> pipeline/<id>/powersets/<at>/<type>/<set>.json shards
//   convert-leveling-schedule -> pipeline/<id>/leveling-schedule.json
//   convert-pool-powers    -> pipeline/<id>/power-pools-raw.json
//   convert-epic-pools     -> pipeline/<id>/epic-pools-raw.json
//   convert-incarnate      -> pipeline/<id>/incarnate-effects.json
//   extract-at-tables      -> pipeline/<id>/at-tables.json
//   convert-archetypes     -> pipeline/<id>/archetype-stats.json (HP/cap/resCap)
//   generate-powerset-index-> pipeline/<id>/powersets.json
//                             (aggregates the shards; needs powersets first)
//   convert-pet-entities   -> pipeline/<id>/pet-entities.json + its three sidecars
const STEPS = [
  // IO set library -> pipeline/<id>/io-sets-raw.json, from the committed export plus
  // `hand-data/homecoming/io-sets-raw.json`. Python, and the only step that is; it shells
  // out to `bridge-attrib-one.cjs` for the attrib bridge. First because
  // `convert-boost-index.cjs` checks its boost index against this library and
  // `convert-powerset.cjs` reads the ATO slotting categories out of it, and both stop
  // rather than skip when it is absent.
  { script: 'extract-rebirth-io-sets-v2.py',  args: [],          generated: true,
    runner: 'python3' },
  { script: 'extract-at-tables.cjs',          args: [],          generated: false },
  // Enhancement curves (SOURCE-1 SW3): ED thresholds, boost-type->schedule,
  // per-level strength curves, multi-aspect ladder, boost_effectiveness ->
  // pipeline/<id>/enhancement-curves.json. Fail-loud on any unrecognized decode.
  { script: 'convert-enhancement-curves.cjs', args: [],          generated: true },
  // Special-enhancement registries (SOURCE-1 item 9): Hamidon/Synthetic/Titan/
  // Hydra/D-Sync/prestige from the boost-piece templates + boosts_allowed ->
  // pipeline/<id>/special-enhancements.json (per dataset; forks carry no D-Sync).
  { script: 'convert-special-enhancements.cjs', args: [],        generated: true },
  // The boost index (BOOST-1): every enhancement keyed by the name the game
  // client prints for it -> pipeline/<id>/boost-index.json. Reads the special
  // registries above to invert them, so it must run after them.
  { script: 'convert-boost-index.cjs',        args: [],          generated: true },
  // Leveling schedule (WS17): power-pick/slot-grant schedules, pool/epic
  // unlocks, per-power auto-granted slot levels -> pipeline/<id>/leveling-schedule.json.
  { script: 'convert-leveling-schedule.cjs',  args: [],          generated: true },
  { script: 'convert-archetypes.cjs',         args: [],          generated: true },
  // The archetype registry itself → pipeline/<id>/archetypes.json: the authored half from
  // hand-data/<id>/archetypes.json merged with the binary stats the line above just wrote.
  // That merge used to be a TypeScript spread resolved at import time, which is what kept
  // `archetypes` as the last row of emit-pipeline-json.cjs's PER_DATASET list. Depends on
  // convert-archetypes.cjs and fails loud without it, so it follows immediately.
  { script: 'convert-archetype-registry.cjs', args: [],          generated: true },
  // Corpus-wide chance-mod selector families (COND-12) -> chance-mod-selectors.json.
  // Every power converter below loads this at startup (convert-powerset.cjs module scope)
  // and fails loud without it, so it must precede them all.
  { script: 'detect-chance-mod-selectors.cjs', args: [],         generated: true },
  // Per-archetype caster meters (COND-13) -> caster-meters.json. Same deal: every power
  // converter loads it at startup and fails loud without it, so it precedes them all. Reads
  // the class tables for the powerset categories, so it follows convert-archetypes.cjs.
  { script: 'detect-caster-meters.cjs',       args: [],          generated: true },
  // Pet entities and the three sidecars convert-powerset.cjs reads off them →
  // pipeline/<id>/pet-entities.json, pet-lifespans.json, self-destruct-delays.json,
  // pet-entity-powers.json.
  //
  // IT RAN NEAR THE FOOT OF THIS LIST UNTIL 2026-09-25, AFTER ITS OWN CONSUMERS, and that only
  // worked because the three sidecars were committed under `src/data/datasets/<id>/`: a consumer
  // running first read LAST regen's copy, so a sidecar change took two runs to reach the powerset
  // tree. The files are ordinary `pipeline/` output now and absence is an error there, so the
  // producer has to precede every consumer — which is here, before the first one. It can sit no
  // earlier: it reads `exported_powers/` plus `convert-powerset.cjs` as a module, and that module
  // loads `chance-mod-selectors.json` and `caster-meters.json` at startup and fails loud without
  // them, so the two detectors above have to come first.
  { script: 'convert-pet-entities.cjs',       args: [],          generated: true },
  { script: 'convert-all-powersets.cjs',      args: ['--force'], generated: true },
  // Archetype-inherent powerset (Vigilance, Containment, …) → pipeline/<id>/inherents.json.
  // emit-contract.cjs merges it into the contract's powersets (Rust-consumed only).
  { script: 'convert-inherents.cjs',          args: [],          generated: true },
  // The universal inherents — Brawl, Sprint, Rest, the free travel toggles, the
  // prestige sprints → pipeline/<id>/basic-inherents.json. It wrote a TypeScript
  // module for levels.ts to import until 2026-09-25, and was the last converter
  // that did. emit-contract.cjs splits the file on category into the two lists
  // levels.ts used to hand every fork Homecoming's copy of.
  { script: 'convert-basic-inherents.cjs',    args: [],          generated: true },
  // Accolades powerset (Atlas Medallion, Freedom Phalanx Reserve, …) →
  // pipeline/<id>/accolades.json. Not yet consumed — the engine still reads the
  // src/data/accolades.ts silo (DATA-GAP ACCOLADE-1 Phase 3+ replaces it).
  { script: 'convert-accolades.cjs',          args: [],          generated: true },
  // Mids' internal name -> ours (MBDIMPORT-2). ABSENT FROM THIS LIST UNTIL 2026-09-24, and
  // that absence is the whole reason the committed table went stale: the converter gained the
  // residual pass and nothing re-ran it, so `reach_for_the_limit` (and `killtk` on Thunderspy)
  // stayed unpaired in the shipped contract while the converter beside it could pair them.
  // Nothing here depends on it and it depends on nothing here — it reads `exported_powers/`
  // and the committed `tools/mids-oracle/mids-power-names.<id>.json` directly — so its only
  // requirement was being named.
  { script: 'convert-mids-name-map.cjs',      args: [],          generated: true },
  { script: 'generate-powerset-index.cjs',    args: [],          generated: false },
  { script: 'convert-pool-powers.cjs',        args: ['--apply'], generated: true },
  { script: 'convert-epic-pools.cjs',         args: ['--apply'], generated: true },
  { script: 'convert-incarnate-effects.cjs',  args: [],          generated: true },
  // `convert-incarnate-slot-indices.cjs` (the per-dataset slot picker indices) and
  // `convert-salvage.cjs` (the invention salvage table) ran here until 2026-09-25. Both
  // wrote TypeScript into `src/data/` and nothing else, so both went with the app; the
  // contract reads salvage straight out of `exported_powers/salvage.json`.
  // Guard: fail the regen if a power's IO-set categories contradict what the power
  // is — a single-target ranged attack offering Melee, say, the signature of a whole
  // category landing on the wrong pool. Runs on the freshly-generated output, so it
  // also gates the CI regen-and-diff pass.
  //
  // What it does NOT see is a category that is merely the wrong NAME for the right
  // pool; that is covered separately, by joining set to power.
  { script: 'audit-allowed-set-categories.cjs', args: ['--gate'], generated: true },
  // DSH3 resistible-twin regression gate: a power whose export carries a
  // resistible + IgnoreResistance debuff twin must keep `unresistable` stamped
  // in the generated output (the exact collapse class fixed 2026-07-05).
  { script: 'validate-converter-output.cjs',    args: ['--gate'], generated: true },
  // DSH8 incarnate per-slot collapse gate (the Support Core defense-drop class).
  // Side effect: rewrites scripts/dsh8-incarnate-collapse-worklist.json — one
  // file, last dataset wins, so the committed copy reflects brainstorm (this
  // loop's final dataset -- ALL_DATASETS ends homecoming, rebirth, thunderspy,
  // brainstorm, and the committed worklist's own `dataset` field says brainstorm;
  // this comment said thunderspy until 2026-09-26). A single-dataset `--dataset` run therefore shows a
  // worklist diff; the full regen restores it (and CI always runs the full set).
  { script: 'dsh8-incarnate-collapse-detector.cjs', args: ['--gate'], generated: true },
];

const steps = generatedOnly ? STEPS.filter((s) => s.generated) : STEPS;

const started = process.hrtime.bigint();

// Export integrity, FIRST, because every step below reads `exported_powers/` as ground truth
// and none of them can tell a real parse from a committed file someone edited afterwards. The
// three checks are staleness (does the recorded fingerprint match the parser source), provenance
// (was it read from the tree `assets_sources.json` sanctions) and contents (are the bytes the
// ones the exporter wrote). 54 checks over 18 manifests, ~14 s — cheap against a regen, and it
// fails before the conversion work rather than after it.
//
// These were documented for months as `src/data/export-staleness.test.ts` and two siblings and
// NEVER EXISTED; the exporters stamped three claims nothing read. Provenance
// self-SKIPS, loudly, where the game is not installed — the two that need only the repository
// still run, so CI gets the tamper check even though it cannot get the path check.
{
  const cmd = 'python3 tools/export-integrity.py --gate';
  console.log(`\n>>> ${cmd}`);
  execSync(cmd, { stdio: 'inherit' });
}

// ...and the fourth question those three deliberately do not ask: has the GAME moved under a
// current export? The three above compare the export to the exporter, to the sanctioned path,
// and to its own digest — all of which stay consistent while the shard patches out from under
// the whole tree. `prov8-shard-drift.cjs` re-hashes the 16 `.pigg` archives the manifests record
// and compares. On 2026-09-20 Homecoming pushed i28p4 RC3 to Brainstorm, Seeker Drones gained
// Ranged AoE Damage on three archetypes, and the first thing that noticed was a USER BUG REPORT.
//
// It was written as a hand-run key on the grounds that it needs the client, so CI cannot run it,
// and "PROV-8 stays open until something runs it on its own". That reasoning kept it out of the
// one place that is always run on a machine that HAS the client. It exits 0 on a dataset whose
// install is absent — SKIPPED, printed, never counted as OK — so it is safe here and silent in
// CI, the same posture as the provenance check above. This is what closes PROV-8.
{
  const cmd = 'node scripts/keys/prov8-shard-drift.cjs --gate';
  console.log(`\n>>> ${cmd}`);
  execSync(cmd, { stdio: 'inherit' });
}

// The one SHARED producer: `PROC_DATABASE` is a single cross-fork table, so its six
// generated side tables are emitted once, not per dataset. Outside the loop for that
// reason and no other — it takes no `--dataset`, and running it four times would write
// the same six files four times. It reads `exported_powers/` plus
// `hand-data/proc-data.json`, the authored base whose key list is its oracle, and neither is
// touched by any step below, so nothing orders it beyond running before the first thing that
// could read what it writes. Like the IO-set extractor it shells out to
// `bridge-attrib-one.cjs` for the attrib bridge, which is why that script stays live.
//
// Its output is `pipeline/_shared/proc-*.json`, which `emit-contract.cjs` staples onto the
// authored base. It wrote six committed TypeScript modules until 2026-09-25; those are frozen
// now and the regen does not touch them.
{
  const cmd = 'python3 scripts/extract-proc-data.py';
  console.log(`\n>>> ${cmd}`);
  execSync(cmd, { stdio: 'inherit' });
}

// The other SHARED producer, and shared for the same kind of reason: the atom tuple's field
// order is one fact about the wire format, the same for every fork. It reads
// `scripts/_atomic-effect.ts` and writes `pipeline/_shared/atom-tuple-fields.json`, which
// `emit-contract.cjs` reads at module load and ships as `contract/schema-version.json`.
//
// `emit-pipeline-json.cjs` wrote this file until 2026-09-25, as the last thing it did that was
// not a straight copy. It is a converter of its own now, named here like any other.
{
  const cmd = 'node scripts/convert-atom-tuple-fields.cjs';
  console.log(`\n>>> ${cmd}`);
  execSync(cmd, { stdio: 'inherit' });
}

for (const ds of datasets) {
  console.log(`\n========== REGEN dataset: ${ds}${generatedOnly ? ' (generated-only)' : ''} ==========`);
  for (const { script, args, runner } of steps) {
    const cmd = `${runner || 'node'} scripts/${script} --dataset ${ds} ${args.join(' ')}`.trim();
    console.log(`\n>>> ${cmd}`);
    execSync(cmd, { stdio: 'inherit' });
  }
}

// DSH6 completeness gate (Phase 0b) — runs ONCE after the dataset loop (the
// detector sweeps the HC generated tree only). Fails the regen if any collapse
// or whole-class-absent group is missing from the frozen allowlist
// (scripts/dsh6-gate-allowlist.json) — the PotD-class silent drop now fails
// here instead of hiding in a non-gating bucket. Side effect: the detector
// rewrites dsh6-collapse-worklist.json, so the CI regen-diff also catches a
// stale committed worklist. Skipped for a single non-HC --dataset run (the
// HC generated tree it checks wasn't touched).
if (datasets.includes('homecoming')) {
  const cmd = 'node scripts/dsh6-collapse-detector.cjs --gate';
  console.log(`\n>>> ${cmd}`);
  execSync(cmd, { stdio: 'inherit' });
}

// def-fidelity gate (parser COMPLETENESS vs authored HC source defs). Diffs the HC
// export's per-power damage typing against the private `.powers` dev drop — the one
// oracle that catches a parser DROP (regression/gate fixtures, generated from our own
// export, structurally cannot).
// Fails on any dropped/mistyped damage type. Self-SKIPS (exit 0, loud) when the defs
// are absent, so it enforces on the self-hosted runner — which has them — and no-ops
// elsewhere. HC-only (the defs are HC). Set COH_RAW_DEFS to relocate the defs.
if (datasets.includes('homecoming')) {
  const cmd = 'python3 tools/defdiff.py --gate';
  console.log(`\n>>> ${cmd}`);
  execSync(cmd, { stdio: 'inherit' });
}

// attrib-completeness gate (parser COMPLETENESS vs authored HC source defs). Where
// def-fidelity above checks per-power damage-type FAITHFULNESS, this checks per-power
// attrib PRESENCE across ALL effect kinds (mez, defense, movement, buffs…): no power
// may DROP an attrib its `.powers` def declares. Structural — attrib presence, never a
// value — so it survives balance patches. Confirmed game-drift is DRIFT_ALLOWLIST'd
// in audit.py. Same self-SKIP + HC-only discipline as the def-fidelity gate.
if (datasets.includes('homecoming')) {
  const cmd = 'python3 tools/extraction-audit/audit.py --gate';
  console.log(`\n>>> ${cmd}`);
  execSync(cmd, { stdio: 'inherit' });
}

// Thunderspy expression-completeness gate (DATA-GAP INHERENT-2). Thunderspy has no `.powers` def
// oracle, so the two HC gates above can't cover it; this is the structural backstop that catches a
// silent re-drop of the magnitude/duration RPN expressions the scan-based parser recovers (Fury's
// `kRage source> .02 *`, the HP-delta/stack scalers, …). Presence-not-value, so it survives balance
// patches. Runs whenever thunderspy is regenerated.
if (datasets.includes('thunderspy')) {
  const cmd = 'node scripts/audit-thunderspy-expressions.cjs';
  console.log(`\n>>> ${cmd}`);
  execSync(cmd, { stdio: 'inherit' });
}

// Damage-type recovery guard — the ÷4 decode map must equal the parser's
// ATTRIB_NAME slice (the one place binary-index knowledge is duplicated into JS),
// every recovered type must be a valid damage element corpus-wide, and the golden
// cases must reproduce exactly. Sweeps ALL datasets from committed exported_powers/
// regardless of --dataset (its inputs are converter logic + committed exports, not
// the tree just regenerated), so it runs unconditionally.
{
  const cmd = 'node scripts/audit-damage-type-recovery.cjs';
  console.log(`\n>>> ${cmd}`);
  execSync(cmd, { stdio: 'inherit' });
}

// Converter-twin shape ratchet — the same game power shipped through two converter
// paths (powerset copy vs pool/epic copy) must keep the same effect-family shape.
// Divergences are findings needing a human eyeball (same-name powers can be genuinely
// different), so this gates against the committed baseline
// (scripts/audit-twins-baseline.json): only a NEW divergence — converter drift, the
// dead-epic-snipe / flat-Soul-Drain class — fails. Adjudicate, then --write-baseline.
{
  const cmd = `node scripts/audit-converter-twins.cjs --gate ${datasets.map((d) => `--dataset ${d}`).join(' ')}`;
  console.log(`\n>>> ${cmd}`);
  execSync(cmd, { stdio: 'inherit' });
}

// Dataset-roster census — the hand-copied fork lists a new dataset falls out of. Adding a
// dataset gains an enum variant, and `cargo` stops at every exhaustive match; a roster written
// as a LITERAL has no such compiler, keeps its old names, and reports PASS over a corpus one
// dataset short. This gate is itself the thing it audits: it shipped wired to nothing, so the
// census that finds silent skips was one for as long as it existed. GATES (exit 1).
{
  const cmd = 'node scripts/audit-dataset-roster.cjs --gate';
  console.log(`\n>>> ${cmd}`);
  execSync(cmd, { stdio: 'inherit' });
}

// Form-detector coverage — every power whose redirect table has the alternate-form shape
// must SHIP that form, whichever of the three converters produced it. The recurring defect
// is not a wrong detector but a converter that never calls one (the epic snipes, the
// pool/epic atom blackout, Aid Other); each was invisible because nothing asserted the
// field was required. Joins the export to the generated tree from outside all three
// converters. GATES (exit 1).
{
  const cmd = `node scripts/audit-form-coverage.cjs --gate ${datasets.map((d) => `--dataset ${d}`).join(' ')}`;
  console.log(`\n>>> ${cmd}`);
  execSync(cmd, { stdio: 'inherit' });
}

// Grant-edge coverage — every served power whose export carries a Self-targeted
// Grant_Power/Revoke_Power edge must ship `grantEdges` deep-equal to the extractor's
// current output, whichever converter produced it. Same defect class as the form gate,
// and its first run proved the point: the inherents and accolades partitions were
// silent until given the call. GATES (exit 1).
{
  const cmd = `node scripts/audit-grant-edges.cjs --gate ${datasets.map((d) => `--dataset ${d}`).join(' ')}`;
  console.log(`\n>>> ${cmd}`);
  execSync(cmd, { stdio: 'inherit' });
}

// Conditional-effect coverage — every power whose export carries a CLASSIFIABLE state gate
// must ship the `conditionalEffects` toggle for it, whichever converter produced it, and the
// per-fork populations and archetype forks are pinned in both directions. Same defect class and
// same outside-the-converters join as the two gates above.
//
// Wired here 2026-08-22, closing BRAIN-3. It existed since COND-2 but was reachable only as
// `npm run audit:conditional-coverage`, and sat in neither this file nor CI — so it went unrun
// long enough for all three pre-existing forks to drift on every axis it pins, while the
// register read zero open. A gate nothing calls grades nothing. GATES (exit 1).
{
  const cmd = `node scripts/audit-conditional-coverage.cjs --gate ${datasets.map((d) => `--dataset ${d}`).join(' ')}`;
  console.log(`\n>>> ${cmd}`);
  execSync(cmd, { stdio: 'inherit' });
}

// Suppress/cancel event-tail coverage — every served Meta atom's event tails
// (suppressEvents/suppressSeconds/suppressAlways/cancelEvents, RB5-d's per-cast clock)
// must match a raw template, every eligible raw tail must ship, and the Hide/Placate
// meter anchors must hold. Re-derives the expectation from the raw export json rather
// than through the shared ingest, so a stamp defect can't grade itself. GATES (exit 1).
{
  const cmd = `node scripts/audit-meter-events.cjs --gate ${datasets.map((d) => `--dataset ${d}`).join(' ')}`;
  console.log(`\n>>> ${cmd}`);
  execSync(cmd, { stdio: 'inherit' });
}

// Coverage-census ratchet — per dataset×converter partition, every effect family's
// atom count. Gates on any EMPTY power (no atoms AND empty bag — zero today) and on
// any structural zero not in scripts/audit-census-baseline.json (standing zeros are
// genuine game facts; a NEW one is a partition blackout, the months-invisible
// "Thunderspy has no movement data" class).
{
  const cmd = `node scripts/audit-coverage-census.cjs --gate ${datasets.map((d) => `--dataset ${d}`).join(' ')}`;
  console.log(`\n>>> ${cmd}`);
  execSync(cmd, { stdio: 'inherit' });
}

// Atom-coverage ratchet — the census above asks whether every effect FAMILY is present in the
// data. This asks the different question of how much of that data the TEST CORPUS reaches:
// 4,929 distinct atom branch-shapes are reachable from player-takeable powers, and the 143
// committed builds in `fixtures/totals/` touch 963 of them (19.5%). Runs in under a second.
//
// It fails two ways, and they mean opposite things. Coverage going DOWN is a corpus regression.
// The shape count CHANGING means the data moved — which is precisely what a re-export or a game
// patch does, and the point at which a frozen answer key stops being comparable. Re-adjudicate
// and `--write-baseline`. Placed after the converters because it reads their output, not the
// export.
{
  const cmd = 'node scripts/audit-atom-coverage.cjs --gate';
  console.log(`\n>>> ${cmd}`);
  execSync(cmd, { stdio: 'inherit' });
}

// THE SIX FIXTURE EMITTERS RAN HERE UNTIL 2026-09-25.
//
// `emit-oracle-fixtures.cjs`, `emit-enhancement-fixtures.cjs`, `emit-totals-fixtures.ts`,
// `emit-proc-fixtures.ts`, `emit-movement-fixtures.ts` and `emit-set-bonus-fixtures.ts`
// each dumped recorded answers out of the TypeScript calculator — `fixtures/oracle`,
// `fixtures/enhancement`, `fixtures/totals`, `fixtures/procs`, `fixtures/movement`,
// `fixtures/set-bonuses`, 48 committed files. They were the last readers of `src/`, so
// they went with it.
//
// Their output stays committed, and stays exactly as the last TS-era run wrote it. Each
// block above said "committed output + CI regen-diff is the guard", and that guard is
// now vacuous for those 48 files: nothing rewrites them, so the diff is clean whatever
// the pipeline does. They are kept anyway, because they are the only surviving record of
// what the reference implementation answered and nothing can produce them again — which
// is a different thing from the 372 empty override stubs deleted alongside them, and the
// reason those went and these did not.

// The contract, last, because it is now what the clean-tree diff actually guards.
//
// Every emitter that used to run above said "committed output + CI clean-tree diff is the
// guard", and that held while the converters wrote committed TypeScript into `src/data`:
// regenerate, and a converter whose output had drifted showed up as a diff. As each converter moves to
// `pipeline/<id>/*.json` that stops being true — `pipeline/` is gitignored, so it can drift
// by any amount and leave the tree spotless. A guard that cannot fail is not a guard.
//
// `contract/` is committed, all 1,446 files of it, so emitting it here restores the property
// and widens it: the diff now covers the artifact the app actually carries, end to end from
// `exported_powers/`, rather than an intermediate on the way to it. A converter change that
// alters no shipped value produces no diff, which is the right answer, and one that alters a
// shipped value produces one, which is the other right answer.
{
  const cmd = 'node scripts/emit-contract.cjs';
  console.log(`\n>>> ${cmd}`);
  execSync(cmd, { stdio: 'inherit' });
}

const secs = Number(process.hrtime.bigint() - started) / 1e9;
console.log(`\n=== regen complete in ${secs.toFixed(0)}s ===`);
