/**
 * Full data regeneration orchestrator.
 *
 * Rebuilds all Node-converter output from the committed `exported_powers/` input
 * (no .pigg / no Python needed), for one or all datasets, in dependency order.
 * This is the single entrypoint the "regen-and-diff" CI guard runs: because the
 * converters embed no timestamps or other non-determinism, a clean working tree
 * before this runs must remain clean after — any diff means the committed output
 * drifted from what the current converters produce.
 *
 * Usage:
 *   node scripts/regen-all.cjs                     # full rebuild, both datasets
 *   node scripts/regen-all.cjs --dataset rebirth   # full rebuild, one dataset
 *   node scripts/regen-all.cjs --generated-only    # only src/data/.../generated/
 *                                                  # (what the CI diff checks)
 *
 * NOT covered (separate pipelines, intentionally excluded):
 *   - IO sets — generated by `extract-rebirth-io-sets-v2.py --dataset <id>`
 *     (both homecoming and rebirth) directly from `boostsets.bin` + `powers.bin`
 *     in the .pigg archives. Python/pigg dependency; writes io-sets-raw.ts, not
 *     generated/. Regenerate manually when boostsets change. (The old
 *     convert-io-sets.js / extract-rebirth-io-sets.cjs predecessors are retired.)
 */

const { execSync } = require('child_process');

const argv = process.argv.slice(2);
const generatedOnly = argv.includes('--generated-only');

const datasets = (() => {
  const i = argv.indexOf('--dataset');
  if (i !== -1 && argv[i + 1]) return [argv[i + 1]];
  // All first-class datasets. Thunderspy is now regenerated by default (its
  // generated/ tree reproduces byte-identical from committed exported_powers/,
  // same as HC/Rebirth) so the regen-diff CI guard covers it too — closing the
  // "converter fix regenerated some datasets, not others" staleness class
  // (the DSH8 Clarion leak).
  return require('./_dataset-paths.cjs').ALL_DATASETS;
})();

// Steps in dependency order. The two that write under generated/ vs the layered
// powersets/ tree are tagged so --generated-only can skip the downstream ones.
// NB convert-pool-powers / convert-epic-pools DRY-RUN unless given --apply, so
// they must carry it here or the orchestrator silently never refreshes
// generated/power-pools.ts + epic-pools.ts (and CI's regen-diff misses pool/epic
// drift entirely).
//   convert-leveling-schedule -> generated/leveling-schedule.ts
//   convert-all-powersets  -> generated/powersets/** (+ composed powersets/**)
//   convert-pool-powers    -> generated/power-pools.ts
//   convert-epic-pools     -> generated/epic-pools.ts
//   convert-incarnate      -> generated/incarnate-effects.ts
//   convert-enhancement-curves -> generated/enhancement-curves.ts (ED/schedules/exemplar)
//   convert-salvage        -> generated/invention-salvage.generated.ts (salvage.bin)
//   extract-at-tables      -> at-tables.ts            (layered, not generated/)
//   convert-archetypes     -> generated/archetype-stats.generated.ts (HP/cap/resCap)
//   generate-powerset-index-> powersets/index.ts      (needs powersets first)
//   convert-pet-entities   -> pet-entities.ts (+ sidecars)
//   convert-archetype-inherents -> generated/archetype-inherents.ts (needs powersets first)
//   convert-boost-index    -> generated/boost-index.ts (needs the special registries)
const STEPS = [
  { script: 'extract-at-tables.cjs',          args: [],          generated: false },
  // Power-pick/slot-grant schedules, pool + epic unlock levels, pool cap and
  // per-power auto-granted slot levels -> generated/leveling-schedule.ts.
  { script: 'convert-leveling-schedule.cjs',  args: [],          generated: true },
  { script: 'convert-archetypes.cjs',         args: [],          generated: true },
  { script: 'convert-all-powersets.cjs',      args: ['--force'], generated: true },
  { script: 'generate-powerset-index.cjs',    args: [],          generated: false },
  // The universal inherents — Brawl, Sprint, Rest, the free travel toggles, the
  // prestige sprints → generated/basic-inherents.ts. Read by levels.ts, which
  // used to spell them out by hand and hand every fork Homecoming's copy.
  { script: 'convert-basic-inherents.cjs',    args: [],          generated: true },
  // Accolade powers -> generated/accolades.ts. Absent from this table until 2026-08-22, so a
  // converter change reached the script and never the output: HELPTEXT-1 shipped with the
  // accolade descriptions still carrying raw `<br>`/`<color>` markup.
  { script: 'convert-accolades.cjs',          args: [],          generated: true },
  { script: 'convert-pool-powers.cjs',        args: ['--apply'], generated: true },
  { script: 'convert-epic-pools.cjs',         args: ['--apply'], generated: true },
  { script: 'convert-incarnate-effects.cjs',  args: [],          generated: true },
  { script: 'convert-enhancement-curves.cjs', args: [],          generated: true },
  { script: 'convert-salvage.cjs',            args: [],          generated: true },
  { script: 'convert-pet-entities.cjs',       args: [],          generated: false },
  // MUST run after convert-all-powersets: it decides an archetype inherent is
  // missing by checking that no powerset already displays that name, so a stale
  // powerset layer would make it emit powers the build can already reach.
  { script: 'convert-archetype-inherents.cjs', args: [],         generated: true },
  // The boost index (BOOST-1): every enhancement keyed by the name the game
  // client prints for it -> generated/boost-index.ts. It INVERTS two layers
  // this list does not own — generated/special-enhancements.ts and
  // io-sets-raw.ts, both refreshed out of band here — so it runs last and
  // throws if either names a record the export does not carry.
  { script: 'convert-boost-index.cjs',        args: [],          generated: true },
  // Guard: fail the regen if a malformed boostset poisoned a whole IO-set
  // category (the Thunderspy "KB"/SumoBoostName pollution class). Runs on the
  // freshly-generated output, so it also gates the CI regen-and-diff pass.
  { script: 'audit-allowed-set-categories.cjs', args: ['--gate'], generated: true },
];

const steps = generatedOnly ? STEPS.filter((s) => s.generated) : STEPS;

const started = process.hrtime.bigint();
for (const ds of datasets) {
  console.log(`\n========== REGEN dataset: ${ds}${generatedOnly ? ' (generated-only)' : ''} ==========`);
  for (const { script, args } of steps) {
    const cmd = `node scripts/${script} --dataset ${ds} ${args.join(' ')}`.trim();
    console.log(`\n>>> ${cmd}`);
    execSync(cmd, { stdio: 'inherit' });
  }
}

// DSH6 completeness gate (Phase 0b) — runs ONCE after the dataset loop (the
// detector sweeps the HC generated tree only). Fails the regen if any collapse
// or whole-class-absent group is missing from the frozen allowlist
// (scripts/dsh6-gate-allowlist.json) — the PotD-class silent drop now fails
// here instead of hiding in a non-gating bucket. Side effect: the detector
// rewrites dsh6-collapse-worklist.json, so the CI regen-diff also catches a
// stale committed worklist. Skipped for a single non-HC --dataset run (the
// HC generated tree it checks wasn't touched).
if (datasets.includes('homecoming')) {
  const cmd = 'node scripts/dsh6-collapse-detector.cjs --gate';
  console.log(`\n>>> ${cmd}`);
  execSync(cmd, { stdio: 'inherit' });
}

// Plan B Phase-1 shadow compare — every discriminator the PowerEffects bag
// carries (the `*Unenhanced` slots, `unresistable`, `toWho:'Self'`,
// `durationVariants`) must be recoverable from the power's atom list. This is
// the precondition for Phase 2 migrating each calc applier off the bag: an
// atom list missing a bag fact would drop it silently. Sweeps every dataset
// just regenerated (~4s), so it also catches an atom-emit regression the
// regen-diff byte gate would see only as churn.
{
  const cmd = `node scripts/planb-shadow-bag.cjs ${datasets.map((d) => `--dataset ${d}`).join(' ')}`;
  console.log(`\n>>> ${cmd}`);
  execSync(cmd, { stdio: 'inherit' });
}

// Plan B Slice 1 — the atom-native ToHit applier (character-totals.ts) reads
// `toHitBuffValue(power)` in place of `effects.tohitBuff`. This gate proves the
// atom reconstruction (scale + converter-stamped perTarget) still reproduces the
// bag exactly, so the per-foe sliders (Soul Drain 1 vs 8 targets) and every
// +ToHit total stay correct after a parser/converter change. GATES (exit 1).
{
  const cmd = `node scripts/planb-shadow-pertarget.cjs ${datasets.map((d) => `--dataset ${d}`).join(' ')}`;
  console.log(`\n>>> ${cmd}`);
  execSync(cmd, { stdio: 'inherit' });
}

// Plan B Slice 3 — the atom-native resistance appliers (character-totals.ts) read
// `resistanceBuffValue(power)` / `resistanceSelfDebuffValue(power)` in place of
// `effects.resistance` / the self-directed `effects.resistanceDebuff` entries. This
// gate proves the per-damage-type reconstruction (scale + converter-stamped
// perTarget — Bio Armor's per-foe Evolving Armor) still reproduces the bag for the
// eight standard resistance globals, so every +Res total and self −Res penalty
// (Offensive Adaptation) stay correct after a parser/converter change. GATES (exit 1).
{
  const cmd = `node scripts/planb-shadow-resistance.cjs ${datasets.map((d) => `--dataset ${d}`).join(' ')}`;
  console.log(`\n>>> ${cmd}`);
  execSync(cmd, { stdio: 'inherit' });
}

// Plan B Slice 4 — the atom-native defense appliers (character-totals.ts) read
// `defenseBuffValue(power)` / `defenseBuffSuppressibleValue(power)` in place of
// `effects.defenseBuff` / `effects.defenseBuffSuppressible`. This gate proves the
// per-position/type reconstruction reproduces the bag for the eleven standard
// defense globals, split on the converter-stamped `suppressible` flag — the FIRST
// slice that needed a converter change to make the atom list complete (until the
// stamp, Hide's always-on +0.25 and combat-suppressed +0.5 defense were
// indistinguishable on the wire). Also covers Invincibility's per-foe +Def via the
// shared perTarget stamp. GATES (exit 1).
{
  const cmd = `node scripts/planb-shadow-defense.cjs ${datasets.map((d) => `--dataset ${d}`).join(' ')}`;
  console.log(`\n>>> ${cmd}`);
  execSync(cmd, { stdio: 'inherit' });
}

// Plan B Slice 5 — the atom-native max-HP appliers (character-totals.ts) read
// `maxHPBuffValue(power)` / `maxHPBuffValue(power, {ignoreStrength:true})` in place
// of `effects.maxHPBuff` / `effects.maxHPBuffUnenhanced`. This gate proves the +MaxHP
// twin (Inexhaustible / High Pain Tolerance / Dull Pain: an enhanceable + an
// IgnoreStrength half that co-apply and sum) reconstructs from atoms split on the
// `ignoreStrength` flag — the first of the `*Unenhanced` twins to fold back into one
// filter. Behavior-preserving (no data change). GATES (exit 1).
{
  const cmd = `node scripts/planb-shadow-maxhp.cjs ${datasets.map((d) => `--dataset ${d}`).join(' ')}`;
  console.log(`\n>>> ${cmd}`);
  execSync(cmd, { stdio: 'inherit' });
}

// Plan B Phase 2 Slice 6 — regen/recovery reconstruction. `character-totals.ts` sources
// all four slots (`regenBuff`/`regenBuffUnenhanced`, `recoveryBuff`/`recoveryBuffUnenhanced`
// — the LAST two `*Unenhanced` twins) from `regenBuffValue`/`recoveryBuffValue`. Unlike
// Slices 1-5 the helper deliberately PUNTS on two shapes it cannot settle from the wire
// (an Expression-typed resource template, and the StackByAttribAndKey burst/tail whose bag
// value is a suspected latent bug), falling back to the unchanged bag; punts are reported,
// not gated. What GATES (exit 1) is every value the helper DOES return — in both
// directions, so an over-production (a phantom total the bag never had, e.g. the Thunderspy
// pet target-trap without its `notOnCaster` stamp) fails just as loudly as a wrong value.
{
  const cmd = `node scripts/planb-shadow-resources.cjs ${datasets.map((d) => `--dataset ${d}`).join(' ')}`;
  console.log(`\n>>> ${cmd}`);
  execSync(cmd, { stdio: 'inherit' });
}
// Plan B Phase 2 Slice 7 — movement reconstruction. `character-totals.ts` sources the
// movement buff map from `movementBuffValue`. Checked in BOTH directions, per axis,
// including the three metadata fields the applier reads (`table` — a movement scale is
// meaningless without it; `stackKey` — the TravelBuff mutual-suppression group, whose
// loss silently stacks CJ + SJ + SS; `suppressible` — combat suppression). GATES (exit 1).
//
// Its printed per-dataset coverage is part of the claim, not decoration: Thunderspy
// scores 0 axis slots because it has NO movement data on either side (it spells the
// attrib `SpeedRunning` where HC spells it `RunningSpeed`, and neither the bag nor the
// bridge maps that), so every Thunderspy travel power yields +0 movement today. This
// gate agrees vacuously about all of it — see the header and CONVERTER-ATOM-ARRAY-PLAN.md.
{
  const cmd = `node scripts/planb-shadow-movement.cjs ${datasets.map((d) => `--dataset ${d}`).join(' ')}`;
  console.log(`\n>>> ${cmd}`);
  execSync(cmd, { stdio: 'inherit' });
}
const secs = Number(process.hrtime.bigint() - started) / 1e9;
console.log(`\n=== regen complete in ${secs.toFixed(0)}s ===`);
